// This file is @generated by prost-build.
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StarkVrfRequest {
    #[prost(string, repeated, tag = "1")]
    pub seed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StarkVrfProof {
    #[prost(string, tag = "1")]
    pub gamma_x: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub gamma_y: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub c: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub s: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub sqrt_ratio: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub rnd: ::prost::alloc::string::String,
}
